# Generated by Django 4.2.4 on 2023-09-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='id платежа на stripe'),
        ),
    ]
